### ISSUE TITLE
How does it work ? (surely dumb question)

### ISSUE THREAD

**Issue by psic** [ellipsis/ellipsis#100]
I love the way that ellipsis should work : add dotfile to package, push package to git. That what I want to do. But I didn't achieve!

First, I create a new package : `ellipsis new` and push it : `ellipsis push` . I was surprise that I push over an elipsis package on ellipsis github. Maybe you should write the option as package name in the help message.
Then I create my package : `ellipsis new mydot`. Add file :`ellipsis add mydot somefile` . It seems to work. On more time, having the parameter ordrer for the add command in the help message will be helpful. I try to push on github :`ellipsis push mydot` . I put my github credential. But, it seems that github complain about having no remote repository to push the package. It's true. I did not create any repo on my github. 
I swear I read the doc. I think I miss something.

**Comment by groggemans** [comment]
Hey psic

GitHub doesn't allow you to create a project by just pushing to a new remote. This means that you always have to create the project in GitHub upfront.

The ellipsis new command is mainly intended to bootstrap a package. But if the project is create in GitHub first it should be possible to just add and push new files.

The first push didn't work, because ellipsis will act on the `ellipsis` package itself if nothing is specified. It's a "feature", but can be confusing.

I do agree that the build in help should be improved. All suggestions are more then welcome!

Gertjan

**Comment by kevinkjt2000** [comment]
`hub create` can make a new repo on GitHub straight from the command line.  You may want to visit this page https://hub.github.com/ and give hub a try.  Since creating a repository on GitHub requires an API key, and ellipsis has no support for interacting with GitHub API keys yet; tools like hub can fill that void for you.

**Comment by groggemans** [comment]
@psic

I'm going to close this issue, don't hesitate to reach out again if you have further questions.
